name: $(Date:yyyyMMdd)-$(Build.BuildId)

trigger:
- main

resources:
- repo: self

variables:
- group: common

extends:
  template: pipeline-template.yaml
  parameters:
      repository: "todoist-webhook"
      multi_arch: "false"